server:
  port: 8081

spring:
  application:
    name: app-postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/bench
    username: bench
    password: bench
    hikari:
      maximum-pool-size: 32
      minimum-idle: 4
      pool-name: bench-pg-pool

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99

logging:
  level:
    root: INFO
    ru.bench: INFO
